name: Promote staging to production

on:
  workflow_dispatch:

concurrency:
  group: promote-production
  cancel-in-progress: false

permissions:
  contents: read
  id-token: write
  actions: write

jobs:
  copy:
    uses: Ari-Kishon/actions/.github/workflows/s3-copy.yml@main
    with:
      source: s3://ariki-tv-staging/trackaos-pad/
      destination: s3://ariki-tv-production/trackaos-pad/
      role-to-assume: arn:aws:iam::583329429936:role/github-actions-upload-to-s3
      destination-role-to-assume: arn:aws:iam::304960797388:role/github-actions-upload-to-s3
      aws-region: eu-west-1

  invalidate:
    needs: copy
    uses: Ari-Kishon/actions/.github/workflows/cloudfront-invalidate.yml@main
    with:
      distribution-id: E2VISORZZDVDA9
      paths: /trackaos-pad /trackaos-pad/*
      role-to-assume: arn:aws:iam::304960797388:role/github-actions-invalidate-cloudfront
